# -*- coding: utf-8 -*-
"""Clase Conjunto_Dinamico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMmPxE-ulCfjolXiBmFXail9_TRE8bbS

---
CLASE CONJUNTO - DINAMICA
---

Concepto Conjunto:

Un conjunto es la agrupación organizada de elementos que comparten una o varias características comunes. Estos elementos pueden ser objetos concretos o abstractos, como números, canciones, meses, personas o planetas.

Concepto Conjunto Dinamico:

Un conjunto dinámico es aquel cuyo tamaño no está fijado de antemano: puede crecer agregando nuevos elementos o reducirse eliminando los existentes durante la ejecución del programa, sin ningún límite predefinido de capacidad.


---
Autor: Karol Josef Aramayo Calle
Resgistro: 224026471
---

# Definicion de la clase - CONJUNTO
"""

class Conjunto:
    """
    Implementación de un Conjunto matemático.

    Cumple con el axioma de extensionalidad: no permite
    elementos duplicados. Soporta las operaciones clásicas
    de la teoría de conjuntos.
    """
    def __init__(self, elementos_iniciales=None):
        """
        Inicializa el conjunto.

        Parametros:
            elementos_iniciales (iterable, optional): Elementos
                con los que se construye el conjunto. Los
                duplicados son ignorados automáticamente.
        """
        self.elementos = []

        if elementos_iniciales is not None:
            for elemento in elementos_iniciales:
                self.agregar(elemento)

    def agregar(self, elemento):
        """
        Añade un elemento al conjunto.

        Valida el axioma de extensionalidad: si el elemento
        ya existe, no se agrega.

        Parametros:
            elemento: El elemento a agregar.
        """
        if elemento not in self.elementos:
            self.elementos.append(elemento)

    def __len__(self):
        """
        Retorna la cardinalidad del conjunto.

        Retorna:
            int: Número de elementos en el conjunto.
        """
        return len(self.elementos)

    def __str__(self):
        """
        Representación en cadena con notación matemática.

        Retorna:
            str: El conjunto con formato {a, b, c}.
        """
        elementos_str = ", ".join(str(e) for e in self.elementos)
        return f"{{{elementos_str}}}"

"""# Métodos y Operaciones

"""

class Conjunto(Conjunto):
    def union(self, otro_conjunto):
        """
        Operación A ∪ B.

        Retorna un nuevo Conjunto con todos los elementos
        de A y de B, sin duplicados.

        Parametros:
            otro_conjunto (Conjunto): El conjunto B.

        Retorna:
            Conjunto: Un nuevo conjunto con la unión.
        """
        resultado = Conjunto(self.elementos)
        for elemento in otro_conjunto.elementos:
            resultado.agregar(elemento)
        return resultado

    def interseccion(self, otro_conjunto):
        """
        Operación A ∩ B.

        Retorna un nuevo Conjunto con los elementos que
        están en A y también en B.

        Parametros:
            otro_conjunto (Conjunto): El conjunto B.

        Retorna:
            Conjunto: Un nuevo conjunto con la intersección.
        """
        resultado = Conjunto()
        for elemento in self.elementos:
            if elemento in otro_conjunto.elementos:
                resultado.agregar(elemento)
        return resultado

    def diferencia(self, otro_conjunto):
        """
        Operación A \\ B.

        Retorna un nuevo Conjunto con los elementos que
        están en A pero NO en B.

        Parametros:
            otro_conjunto (Conjunto): El conjunto B.

        Retorna:
            Conjunto: Un nuevo conjunto con la diferencia.
        """
        resultado = Conjunto()
        for elemento in self.elementos:
            if elemento not in otro_conjunto.elementos:
                resultado.agregar(elemento)
        return resultado

    def diferencia_simetrica(self, otro_conjunto):
        """
        Operación A △ B.

        Retorna un nuevo Conjunto con los elementos que
        están en A o en B, pero NO en ambos.

        Parametros:
            otro_conjunto (Conjunto): El conjunto B.

        Retorna:
            Conjunto: Un nuevo conjunto con la diferencia simétrica.
        """
        return self.union(otro_conjunto).diferencia(
            self.interseccion(otro_conjunto)
        )
    def eliminar(self, elemento):
          """
          Elimina un elemento del conjunto.

          Parametros:
              elemento (int): El elemento a eliminar.

          Retorna:
              KeyError: Si el elemento no existe en el conjunto.
          """
          if elemento not in self.elementos:
              raise KeyError(
                  f"El elemento {elemento!r} no existe en el conjunto."
              )
          self.elementos.remove(elemento)

"""# Uso y Pruebas

"""

conjunto_a = Conjunto([1, 2, 3, 4, 4, 4])
conjunto_b = Conjunto([3, 4, 5, 6])

print(f"Conjunto A: {conjunto_a}  (Cardinalidad: {len(conjunto_a)})")
print(f"Conjunto B: {conjunto_b}  (Cardinalidad: {len(conjunto_b)})")
print("-" * 43)
# Operaciones
print(f"Unión          (A ∪ B):  {conjunto_a.union(conjunto_b)}")
print(f"Intersección   (A ∩ B):  {conjunto_a.interseccion(conjunto_b)}")
print(f"Diferencia     (A \\ B):  {conjunto_a.diferencia(conjunto_b)}")
print(f"Dif. Simétrica (A △ B):  {conjunto_a.diferencia_simetrica(conjunto_b)}")
print("-" * 43)
conjunto_a.eliminar(3)
print(f"A tras eliminar 3: {conjunto_a}")
# conjunto vacio
conjunto_vacio = Conjunto()
print(f"Conjunto vacío: {conjunto_vacio}")