# -*- coding: utf-8 -*-
"""Clase Conjunto_Persistente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CFri6lGqahoF8gGrLXJUK-2VluyQUYbQ

---
CLASE CONJUNTO - PERSISTENTE

---

Concepto Conjunto:

Un conjunto es la agrupación organizada de elementos que comparten una o varias características comunes. Estos elementos pueden ser objetos concretos o abstractos, como números, canciones, meses, personas o planetas.

Concepto Conjunto Persistente:

Un conjunto persistente es aquel cuyo estado se guarda en un medio de almacenamiento externo, como un archivo JSON o una base de datos, de forma que sus elementos no se pierden al cerrar el programa. Al volver a ejecutarlo, el conjunto puede recuperar automáticamente los datos guardados y continuar desde donde se dejó.


---
Autor: Karol Josef Aramayo Calle
Resgistro: 224026471
---

# Definicion de la clase - CONJUNTO
"""

import json
import os


class ConjuntoPersistente:
    """
    Implementación de un Conjunto matemático persistente.

    Cumple con el axioma de extensionalidad: no permite
    elementos duplicados. Su estado se guarda automáticamente
    en un archivo JSON y puede recuperarse entre ejecuciones.
    """

    def __init__(self, nombre_archivo, elementos_iniciales=None):
        """
        Inicializa el conjunto persistente.

        Si el archivo ya existe, carga los datos guardados.
        Si no existe, crea un conjunto nuevo y lo guarda.

        Parametros:
            nombre_archivo (str): Nombre del archivo JSON
                sin extensión.
            elementos_iniciales (iterable, optional): Elementos
                con los que se construye el conjunto si el archivo
                no existe aún. Los duplicados son ignorados.

        Raises:
            TypeError: Si nombre_archivo no es una cadena válida.
        """
        if not isinstance(nombre_archivo, str) or not nombre_archivo.strip():
            raise TypeError(
                "El nombre de archivo debe ser una cadena no vacía."
            )

        self.nombre_archivo = f"{nombre_archivo}.json"
        self.elementos = []

        if os.path.exists(self.nombre_archivo):
            self._cargar()
            print(f"[INFO] Conjunto cargado desde '{self.nombre_archivo}'.")
        else:
            if elementos_iniciales is not None:
                for elemento in elementos_iniciales:
                    self.agregar(elemento)
            self._guardar()
            print(f"[INFO] Conjunto nuevo guardado en '{self.nombre_archivo}'.")

    def agregar(self, elemento):
        """
        Añade un elemento y guarda automáticamente en disco.

        Parametros:
            elemento (int): El elemento a agregar.

        Raises:
            TypeError: Si el elemento no es un entero.
        """
        if not isinstance(elemento, int):
            raise TypeError(
                f"Solo se permiten enteros. "
                f"Se recibió '{type(elemento).__name__}': {elemento!r}."
            )
        if elemento not in self.elementos:
            self.elementos.append(elemento)
            self._guardar()

    def eliminar(self, elemento):
        """
        Elimina un elemento y guarda automáticamente en disco.

        Parametros:
            elemento (int): El elemento a eliminar.

        Raises:
            KeyError: Si el elemento no existe en el conjunto.
        """
        if elemento not in self.elementos:
            raise KeyError(
                f"El elemento {elemento!r} no existe en el conjunto."
            )
        self.elementos.remove(elemento)
        self._guardar()

    def _guardar(self):
        """
        Guarda el estado actual en el archivo JSON.

        Retorna:
            None
        """
        with open(self.nombre_archivo, "w", encoding="utf-8") as archivo:
            json.dump({"elementos": self.elementos}, archivo, indent=4)

    def _cargar(self):
        """
        Carga el estado desde el archivo JSON.

        Retorna:
            None
        """
        with open(self.nombre_archivo, "r", encoding="utf-8") as archivo:
            datos = json.load(archivo)
            self.elementos = datos.get("elementos", [])

    def eliminar_archivo(self):
        """
        Borra el archivo JSON del disco.

        Retorna:
            None
        """
        if os.path.exists(self.nombre_archivo):
            os.remove(self.nombre_archivo)
            print(f"[INFO] Archivo '{self.nombre_archivo}' eliminado.")

    def esta_vacio(self):
        """
        Verifica si el conjunto no tiene elementos.

        Retorna:
            bool: True si está vacío, False si no.
        """
        return len(self.elementos) == 0

    def __len__(self):
        """
        Retorna la cardinalidad del conjunto.

        Retorna:
            int: Número de elementos en el conjunto.
        """
        return len(self.elementos)

    def __contains__(self, elemento):
        """
        Permite usar el operador 'in' directamente.

        Parametros:
            elemento (int): El elemento a buscar.

        Retorna:
            bool: True si el elemento pertenece al conjunto.
        """
        return elemento in self.elementos

    def __eq__(self, otro):
        """
        Permite usar el operador '==' directamente.

        Parametros:
            otro (ConjuntoPersistente): El conjunto a comparar.

        Retorna:
            bool: True si ambos conjuntos tienen los mismos elementos.
        """
        if not isinstance(otro, ConjuntoPersistente):
            return False
        return sorted(self.elementos) == sorted(otro.elementos)

    def __str__(self):
        """
        Representación en cadena con notación matemática.

        Retorna:
            str: El conjunto con formato {a, b, c}
                 o '∅' si está vacío.
        """
        if self.esta_vacio():
            return "∅"
        elementos_str = ", ".join(str(e) for e in self.elementos)
        return f"{{{elementos_str}}}"

"""# Métodos y Operaciones

"""

class ConjuntoPersistente(ConjuntoPersistente):

    def union(self, otro):
        """
        Operación A ∪ B.

        El resultado se guarda en un archivo temporal.

        Parametros:
            otro (ConjuntoPersistente): El conjunto B.

        Retorna:
            ConjuntoPersistente: Un nuevo conjunto con la unión.
        """
        resultado = ConjuntoPersistente("_temp_union", self.elementos)
        for elemento in otro.elementos:
            resultado.agregar(elemento)
        return resultado

    def interseccion(self, otro):
        """
        Operación A ∩ B.

        Parametros:
            otro (ConjuntoPersistente): El conjunto B.

        Retorna:
            ConjuntoPersistente: Un nuevo conjunto con la intersección.
        """
        resultado = ConjuntoPersistente("_temp_interseccion")
        for elemento in self.elementos:
            if elemento in otro.elementos:
                resultado.agregar(elemento)
        return resultado

    def diferencia(self, otro):
        """
        Operación A \\ B.

        Parametros:
            otro (ConjuntoPersistente): El conjunto B.

        Retorna:
            ConjuntoPersistente: Un nuevo conjunto con la diferencia.
        """
        resultado = ConjuntoPersistente("_temp_diferencia")
        for elemento in self.elementos:
            if elemento not in otro.elementos:
                resultado.agregar(elemento)
        return resultado

    def complemento(self, universal):
        """
        Operación A' respecto a U.

        Parametros:
            universal (ConjuntoPersistente): El conjunto universal U.

        Retorna:
            ConjuntoPersistente: Un nuevo conjunto con el complemento.
        """
        return universal.diferencia(self)

    def son_disjuntos(self, otro):
        """
        Verifica si A y B no comparten ningún elemento.

        Parametros:
            otro (ConjuntoPersistente): El conjunto B.

        Retorna:
            bool: True si A ∩ B = ∅, False si no.
        """
        return self.interseccion(otro).esta_vacio()

"""# Uso y Pruebas

"""

a = ConjuntoPersistente("conjunto_a", [1, 2, 3, 4])
b = ConjuntoPersistente("conjunto_b", [3, 4, 5, 6])
u = ConjuntoPersistente("conjunto_u", [1, 2, 3, 4, 5, 6, 7, 8])

print(f"A: {a}  (cardinalidad: {len(a)})")
print(f"B: {b}")
print("-" * 40)
print(f"A ∪ B:       {a.union(b)}")
print(f"A ∩ B:       {a.interseccion(b)}")
print(f"A \\ B:       {a.diferencia(b)}")
print(f"A':          {a.complemento(u)}")
print(f"¿Disjuntos?  {a.son_disjuntos(b)}")
print("-" * 40)

# Modificar y verificar que se guarda
a.agregar(99)
print(f"A tras agregar 99:   {a}")
a.eliminar(99)
print(f"A tras eliminar 99:  {a}")
print("-" * 40)

# Segunda ejecución: carga automáticamente desde los archivos
a2 = ConjuntoPersistente("conjunto_a")
print(f"A recuperado desde disco: {a2}")
print("-" * 40)

# Limpieza de archivos
a.eliminar_archivo()
b.eliminar_archivo()
u.eliminar_archivo()
a.union(b).eliminar_archivo()
a.interseccion(b).eliminar_archivo()
a.diferencia(b).eliminar_archivo()