# -*- coding: utf-8 -*-
"""Clase Conjunto_Estatico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RKiNp9CxMG04-0gpbIl3mzYLdspZ3lxd

---
CLASE CONJUNTO - ESTATICO
---

Concepto Conjunto:

Un conjunto es la agrupación organizada de elementos que comparten una o varias características comunes. Estos elementos pueden ser objetos concretos o abstractos, como números, canciones, meses, personas o planetas.

Concepto Conjunto Estatico:

Un conjunto estático es aquel cuya capacidad máxima se define en el momento de su creación y no puede ser modificada. Una vez que alcanza ese límite, no es posible agregar más elementos, lo que garantiza un uso de memoria fijo y predecible durante toda la ejecución del programa.


---
Autor: Karol Josef Aramayo Calle
Resgistro: 224026471
---

# Definicion de la clase - CONJUNTO
"""

class ConjuntoEstatico:
    """
    Implementación de un Conjunto matemático estático.

    Cumple con el axioma de extensionalidad: no permite
    elementos duplicados. Su capacidad máxima se define
    al momento de la creación y no puede modificarse.
    """

    def __init__(self, capacidad_maxima, elementos_iniciales=None):
        """
        Inicializa el conjunto estático.

        Parametros:
            capacidad_maxima (int): Límite máximo de elementos.
            elementos_iniciales (iterable, optional): Elementos
                con los que se construye el conjunto. Los
                duplicados son ignorados automáticamente.

        Raises:
            TypeError: Si capacidad_maxima no es un entero positivo.
            OverflowError: Si los elementos iniciales superan la capacidad.
        """
        if not isinstance(capacidad_maxima, int) or capacidad_maxima <= 0:
            raise TypeError(
                f"La capacidad debe ser un entero positivo. "
                f"Se recibió: {capacidad_maxima!r}."
            )

        self.capacidad_maxima = capacidad_maxima
        self.elementos = []

        if elementos_iniciales is not None:
            for elemento in elementos_iniciales:
                self.agregar(elemento)

    def agregar(self, elemento):
        """
        Añade un elemento respetando la capacidad máxima.

        Parametros:
            elemento (int): El elemento a agregar.

        Raises:
            TypeError: Si el elemento no es un entero.
            OverflowError: Si el conjunto ya alcanzó su capacidad.
        """
        if not isinstance(elemento, int):
            raise TypeError(
                f"Solo se permiten enteros. "
                f"Se recibió '{type(elemento).__name__}': {elemento!r}."
            )
        if len(self.elementos) >= self.capacidad_maxima:
            raise OverflowError(
                f"Conjunto lleno. Capacidad máxima: {self.capacidad_maxima}."
            )
        if elemento not in self.elementos:
            self.elementos.append(elemento)

    def esta_lleno(self):
        """
        Verifica si el conjunto alcanzó su capacidad máxima.

        Retorna:
            bool: True si está lleno, False si no.
        """
        return len(self.elementos) == self.capacidad_maxima

    def esta_vacio(self):
        """
        Verifica si el conjunto no tiene elementos.

        Retorna:
            bool: True si está vacío, False si no.
        """
        return len(self.elementos) == 0

    def __len__(self):
        """
        Retorna la cardinalidad del conjunto.

        Retorna:
            int: Número de elementos en el conjunto.
        """
        return len(self.elementos)

    def __contains__(self, elemento):
        """
        Permite usar el operador 'in' directamente.

        Parametros:
            elemento (int): El elemento a buscar.

        Retorna:
            bool: True si el elemento pertenece al conjunto.
        """
        return elemento in self.elementos

    def __eq__(self, otro):
        """
        Permite usar el operador '==' directamente.

        Parametros:
            otro (ConjuntoEstatico): El conjunto a comparar.

        Retorna:
            bool: True si ambos conjuntos tienen los mismos elementos.
        """
        if not isinstance(otro, ConjuntoEstatico):
            return False
        return sorted(self.elementos) == sorted(otro.elementos)

    def __str__(self):
        """
        Representación en cadena con notación matemática.

        Retorna:
            str: El conjunto con formato {a, b, c}
                 o '∅' si está vacío.
        """
        if self.esta_vacio():
            return "∅"
        elementos_str = ", ".join(str(e) for e in self.elementos)
        return f"{{{elementos_str}}}"

"""# Métodos y Operaciones

"""

class ConjuntoEstatico(ConjuntoEstatico):

    def union(self, otro):
        """
        Operación A ∪ B.

        La capacidad del resultado es la suma de ambas capacidades.

        Parametros:
            otro (ConjuntoEstatico): El conjunto B.

        Retorna:
            ConjuntoEstatico: Un nuevo conjunto con la unión.
        """
        capacidad = self.capacidad_maxima + otro.capacidad_maxima
        resultado = ConjuntoEstatico(capacidad, self.elementos)
        for elemento in otro.elementos:
            resultado.agregar(elemento)
        return resultado

    def interseccion(self, otro):
        """
        Operación A ∩ B.

        Parametros:
            otro (ConjuntoEstatico): El conjunto B.

        Retorna:
            ConjuntoEstatico: Un nuevo conjunto con la intersección.
        """
        capacidad = min(self.capacidad_maxima, otro.capacidad_maxima)
        resultado = ConjuntoEstatico(capacidad if capacidad > 0 else 1)
        for elemento in self.elementos:
            if elemento in otro.elementos:
                resultado.agregar(elemento)
        return resultado

    def diferencia(self, otro):
        """
        Operación A \\ B.

        Parametros:
            otro (ConjuntoEstatico): El conjunto B.

        Retorna:
            ConjuntoEstatico: Un nuevo conjunto con la diferencia.
        """
        resultado = ConjuntoEstatico(self.capacidad_maxima)
        for elemento in self.elementos:
            if elemento not in otro.elementos:
                resultado.agregar(elemento)
        return resultado

    def complemento(self, universal):
        """
        Operación A' respecto a U.

        Parametros:
            universal (ConjuntoEstatico): El conjunto universal U.

        Retorna:
            ConjuntoEstatico: Un nuevo conjunto con el complemento.
        """
        return universal.diferencia(self)

    def son_disjuntos(self, otro):
        """
        Verifica si A y B no comparten ningún elemento.

        Parametros:
            otro (ConjuntoEstatico): El conjunto B.

        Retorna:
            bool: True si A ∩ B = ∅, False si no.
        """
        return self.interseccion(otro).esta_vacio()

"""# Uso y Pruebas

"""

a = ConjuntoEstatico(5, [1, 2, 3])
b = ConjuntoEstatico(5, [3, 4, 5])
u = ConjuntoEstatico(10, [1, 2, 3, 4, 5, 6, 7])

print(f"A:            {a}  (capacidad: {a.capacidad_maxima})")
print(f"B:            {b}  (capacidad: {b.capacidad_maxima})")
print(f"¿A lleno?     {a.esta_lleno()}")
print("-" * 40)
print(f"A ∪ B:        {a.union(b)}")
print(f"A ∩ B:        {a.interseccion(b)}")
print(f"A \\ B:        {a.diferencia(b)}")
print(f"A':           {a.complemento(u)}")
print(f"¿Disjuntos?   {a.son_disjuntos(b)}")
print("-" * 40)

# Error esperado — conjunto lleno
a_lleno = ConjuntoEstatico(3, [1, 2, 3])
try:
    a_lleno.agregar(4)
except OverflowError as e:
    print(f"[OverflowError] {e}")