# -*- coding: utf-8 -*-
"""CLASE _ POLINOMIO_ARREGLO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KUXte0Wg4k505yUklEtE5v7Nez1qYfsN

---
CLASE Polinomio - Arreglo
---

Concepto Polinomio:
Un polinomio es una funcion real sobre una variable, que tiene la forma:
P(x) = 3x124 + 4x11 - 8x3 + 6x - 9 donde:
Grado = 124,Coef. = 3Numero de terminos 5  ordenada de mayor a menor exponente



Concepto Polinomio - Arreglo:
Se utiliza un arreglo (vector) donde la posición A[i] almacena el coeficiente del término de grado
.
---
Autor: Karol Josef Aramayo Calle
Resgistro: 224026471
---

# Definicion de la clase
"""

class PolinomioArreglo:
    """
    Implementación de un Polinomio usando un arreglo (lista).

    El índice de cada posición representa el exponente y
    el valor en esa posición representa el coeficiente.

    Ejemplo:
        [3, 0, 2, 1] representa: 1x³ + 2x² + 0x + 3
    """

    def __init__(self, coeficientes=None):
        """
        Inicializa el polinomio.

        Parametros:
            coeficientes (list, optional): Lista de enteros donde
                el índice es el exponente. Si no se proporciona,
                se crea un polinomio vacío.

        Raises:
            TypeError: Si coeficientes no es una lista.
            TypeError: Si algún coeficiente no es entero.
        """
        if coeficientes is None:
            self.coeficientes = []
        else:
            # Se redujo a una sola validación fundamental
            if not isinstance(coeficientes, list):
                raise TypeError("Se esperaba una lista.")
            self.coeficientes = coeficientes

    # ─────────────────────────────────────────
    # GETTERS
    # ─────────────────────────────────────────

    def get_coeficiente(self, exponente):
        """
        Retorna el coeficiente de un exponente dado.

        Parametros:
            exponente (int): El exponente a consultar.

        Retorna:
            int: El coeficiente. Retorna 0 si el exponente
                 no existe en el polinomio.
        """
        if exponente >= len(self.coeficientes):
            return 0
        return self.coeficientes[exponente]

    def get_grado(self):
        """
        Retorna el grado del polinomio (mayor exponente
        con coeficiente distinto de cero).

        Retorna:
            int: El grado del polinomio. Retorna -1 si
                 el polinomio está vacío.
        """
        for i in range(len(self.coeficientes) - 1, -1, -1):
            if self.coeficientes[i] != 0:
                return i
        return -1

    def get_coeficiente_lider(self):
        """
        Retorna el coeficiente del término de mayor grado.

        Retorna:
            int: El coeficiente líder. Retorna 0 si el
                 polinomio está vacío.
        """
        grado = self.get_grado()
        if grado == -1:
            return 0
        return self.coeficientes[grado]

    def get_terminos(self):
        """
        Retorna una lista de tuplas (coeficiente, exponente)
        de los términos con coeficiente distinto de cero.

        Retorna:
            list: Lista de tuplas (coeficiente, exponente)
                  ordenada de mayor a menor exponente.
        """
        return [
            (self.coeficientes[i], i)
            for i in range(len(self.coeficientes) - 1, -1, -1)
            if self.coeficientes[i] != 0
        ]

    def esta_vacio(self):
        """
        Verifica si el polinomio no tiene términos.

        Retorna:
            bool: True si está vacío, False si no.
        """
        return self.get_grado() == -1

    def __str__(self):
        """
        Representación en cadena del polinomio.

        Retorna:
            str: El polinomio en notación matemática.
                 Ejemplo: 1x³ + 2x² + 3
        """
        terminos = self.get_terminos()
        if not terminos:
            return "0"

        partes = []
        for coef, exp in terminos:
            if exp == 0:
                partes.append(str(coef))
            elif exp == 1:
                partes.append(f"{coef}x")
            else:
                partes.append(f"{coef}x^{exp}")

        return " + ".join(partes).replace("+ -", "- ")

"""# Métodos y Operaciones

"""

class PolinomioArreglo(PolinomioArreglo):

  def sumar(self, otro):
        """
        Suma dos polinomios A + B.

        Parametros:
            otro (PolinomioArreglo): El polinomio B.

        Retorna:
            PolinomioArreglo: Un nuevo polinomio con la suma.

        Raises:
            TypeError: Si otro no es un PolinomioArreglo.
        """
        if not isinstance(otro, PolinomioArreglo):
            raise TypeError("Se esperaba un PolinomioArreglo.")

        longitud = max(len(self.coeficientes), len(otro.coeficientes))
        resultado = []
        for i in range(longitud):
            resultado.append(self.get_coeficiente(i) + otro.get_coeficiente(i))
        return PolinomioArreglo(resultado)

  def restar(self, otro):
        """
        Resta dos polinomios A - B.

        Parametros:
            otro (PolinomioArreglo): El polinomio B.

        Retorna:
            PolinomioArreglo: Un nuevo polinomio con la resta.

        Raises:
            TypeError: Si otro no es un PolinomioArreglo.
        """
        if not isinstance(otro, PolinomioArreglo):
            raise TypeError("Se esperaba un PolinomioArreglo.")

        longitud = max(len(self.coeficientes), len(otro.coeficientes))
        resultado = []
        for i in range(longitud):
            resultado.append(self.get_coeficiente(i) - otro.get_coeficiente(i))
        return PolinomioArreglo(resultado)

  def multiplicar(self, otro):
        """
        Multiplica dos polinomios A * B.

        Parametros:
            otro (PolinomioArreglo): El polinomio B.

        Retorna:
            PolinomioArreglo: Un nuevo polinomio con el producto.

        Raises:
            TypeError: Si otro no es un PolinomioArreglo.
        """
        if not isinstance(otro, PolinomioArreglo):
            raise TypeError("Se esperaba un PolinomioArreglo.")

        grado_resultado = self.get_grado() + otro.get_grado()
        resultado = [0] * (grado_resultado + 1)
        for i, c1 in enumerate(self.coeficientes):
            for j, c2 in enumerate(otro.coeficientes):
                resultado[i + j] += c1 * c2
        return PolinomioArreglo(resultado)

  def dividir(self, otro):
        """
        Divide dos polinomios A / B usando división larga.

        Parametros:
            otro (PolinomioArreglo): El divisor B.

        Retorna:
            tuple: (cociente, residuo) ambos PolinomioArreglo.

        Raises:
            TypeError: Si otro no es un PolinomioArreglo.
            ZeroDivisionError: Si el divisor es el polinomio cero.
        """
        if otro.esta_vacio():
            raise ZeroDivisionError("No se puede dividir por el polinomio cero.")

        dividendo = list(self.coeficientes)
        divisor = otro.coeficientes
        grado_div = otro.get_grado()
        cociente = [0] * (len(dividendo))

        for i in range(len(dividendo) - 1, grado_div - 1, -1):
            if divisor[grado_div] == 0:
                continue
            factor = dividendo[i] // divisor[grado_div]
            cociente[i - grado_div] = factor
            for j in range(grado_div + 1):
                dividendo[i - grado_div + j] -= factor * divisor[j]

        residuo = PolinomioArreglo(dividendo[:grado_div])
        return PolinomioArreglo(cociente), residuo

  def evaluar(self, x):
        """
        Evalúa el polinomio en un punto dado usando la
        regla de Horner.

        Parametros:
            x (int): El valor en el que se evalúa el polinomio.

        Retorna:
            int: El resultado de evaluar el polinomio en x.

        Raises:
            TypeError: Si x no es un entero.
        """
        if not isinstance(x, int):
            raise TypeError("Solo se permiten valores enteros para x.")

        resultado = 0
        for i in range(len(self.coeficientes) - 1, -1, -1):
            resultado = resultado * x + self.coeficientes[i]
        return resultado

  def derivar(self):
        """
        Calcula la derivada del polinomio.

        Retorna:
            PolinomioArreglo: Un nuevo polinomio con la derivada.
        """
        if len(self.coeficientes) <= 1:
            return PolinomioArreglo([0])
        resultado = []
        for i in range(1, len(self.coeficientes)):
            resultado.append(i * self.coeficientes[i])
        return PolinomioArreglo(resultado)

"""# Uso y Pruebas

"""

p1 = PolinomioArreglo([3, 0, 2, 1])    # Representa: 1x³ + 2x² + 3
p2 = PolinomioArreglo([1, 2, 1])       # Representa: 1x² + 2x + 1

print(f"P1:            {p1}")
print(f"P2:            {p2}")
print(f"Grado P1:      {p1.get_grado()}")
print(f"Coef. líder:   {p1.get_coeficiente_lider()}")
print(f"Términos P1:   {p1.get_terminos()}")

print("-" * 40)

print(f"P1 + P2:       {p1.sumar(p2)}")
print(f"P1 - P2:       {p1.restar(p2)}")
print(f"P1 * P2:       {p1.multiplicar(p2)}")
print(f"P1 evaluado en x=2:  {p1.evaluar(2)}")
print(f"Derivada P1:   {p1.derivar()}")

print("-" * 40)

cociente, residuo = p1.dividir(p2)
print(f"P1 / P2:")
print(f"  Cociente:    {cociente}")
print(f"  Residuo:     {residuo}")