# -*- coding: utf-8 -*-
"""POLINOMIO_LISTA_ENLAZADAS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16DWoU__jISCKeeDvQ-eHmSvayBt_tKxp

---
CLASE POLINOMIO - LISTA ENLAZADAS
---
Concepto POLINOMIO:
---
Concepto Polinomio: Un polinomio es una funcion real sobre una variable, que tiene la forma: P(x) = 3x124 + 4x11 - 8x3 + 6x - 9 donde: Grado = 124,Coef. = 3Numero de terminos 5 ordenada de mayor a menor exponente
---
Concepto POLINOMIO - Lista Enlazada:
---
Un polinomio representado mediante listas enlazadas es una estructura de datos dinámica donde cada nodo almacena un término del polinomio, compuesto por coeficiente, exponente y un puntero al siguiente término.
---
Autor: Karol Josef Aramayo Calle
Resgistro: 224026471
---

# Definicion de la clase
"""

class NodoPolinomio:
    """
    Nodo de la lista enlazada que representa un término
    del polinomio.

    Cada nodo almacena un coeficiente, su exponente
    y una referencia al siguiente nodo.
    """

    def __init__(self, coeficiente, exponente):
        """
        Inicializa el nodo.

        Parametros:
            coeficiente (int): El coeficiente del término.
            exponente (int): El exponente del término.

        Raises:
            ValueError: Si el exponente no es válido matemáticamente.
        """
        if not isinstance(exponente, int) or exponente < 0:
            raise ValueError("El exponente debe ser un entero no negativo")

        self.coeficiente = coeficiente
        self.exponente = exponente
        self.siguiente = None

"""# Métodos y Operaciones

"""

class polinomio:
    """
    Implementación de un Polinomio usando una lista enlazada.

    Cada nodo representa un término algebraico definido por un escalar (coeficiente)
    y una potencia (exponente). La topología se mantiene ordenada de forma estricta
    de mayor a menor exponente, garantizando que el nodo cabecera contenga siempre
    el término que dicta el grado del polinomio.
    """

    def __init__(self):
        """
        Inicializa la estructura del polinomio en un estado nulo.

        Parametros:
            Ninguno.

        Retorna:
            Ninguno. Establece la cabeza de la secuencia topológica como vacía.
        """
        self.cabeza = None

    def agregar_termino(self, coeficiente, exponente):
        """
        Incorpora un nuevo término algebraico al modelo matemático, preservando
        el orden descendente de los exponentes. Si se introduce un término con
        un exponente ya existente, aplica el principio de superposición, sumando
        algebraicamente sus coeficientes.

        Parametros:
            coeficiente (int): El valor escalar que multiplica a la variable.
            exponente (int): La potencia a la que está elevada la variable.

        Retorna:
            Ninguno. Modifica la estructura interna del objeto.
        """
        # Evitamos inyectar masa nula al sistema desde el principio
        if coeficiente == 0:
            return

        nuevo = NodoPolinomio(coeficiente, exponente)

        if self.cabeza is None or exponente > self.cabeza.exponente:
            nuevo.siguiente = self.cabeza
            self.cabeza = nuevo
            return

        actual = self.cabeza
        while actual is not None:
            if actual.exponente == exponente:
                actual.coeficiente += coeficiente
                return
            if actual.siguiente is None or exponente > actual.siguiente.exponente:
                nuevo.siguiente = actual.siguiente
                actual.siguiente = nuevo
                return
            actual = actual.siguiente

    # ─────────────────────────────────────────
    # GETTERS (Propiedades de Observación)
    # ─────────────────────────────────────────

    def get_cabeza(self):
        """
        Extrae el nodo fundamental de la estructura enlazada, que representa
        el término de mayor jerarquía en la ecuación.

        Parametros:
            Ninguno.

        Retorna:
            NodoPolinomio: La entidad que contiene el término de mayor grado,
                           o None si el polinomio carece de términos.
        """
        return self.cabeza

    def get_grado(self):
        """
        Evalúa el grado absoluto del polinomio, que corresponde matemáticamente
        al exponente de mayor magnitud en toda la expresión.

        Parametros:
            Ninguno.

        Retorna:
            int: El grado máximo. Si el polinomio es el polinomio nulo,
                 retorna -1 por convención matemática estándar.
        """
        if self.cabeza is None:
            return -1
        return self.cabeza.exponente

    def get_coeficiente_lider(self):
        """
        Identifica el coeficiente principal de la expresión matemática. Es el
        escalar asociado a la variable de mayor exponente.

        Parametros:
            Ninguno.

        Retorna:
            int: El valor numérico del coeficiente líder. Retorna 0 si el
                 modelo está vacío.
        """
        if self.cabeza is None:
            return 0
        return self.cabeza.coeficiente

    def get_coeficiente(self, exponente):
        """
        Localiza el escalar específico que acompaña a una potencia particular
        dentro de la serie del polinomio.

        Parametros:
            exponente (int): El grado del término a consultar.

        Retorna:
            int: El coeficiente encontrado. Si el grado no existe en la ecuación,
                 se deduce que el término es nulo y retorna 0.
        """
        actual = self.cabeza
        while actual is not None:
            if actual.exponente == exponente:
                return actual.coeficiente
            actual = actual.siguiente
        return 0

    def get_terminos(self):
        """
        Proyecta la estructura enlazada en una lista secuencial de coordenadas
        bidimensionales, facilitando su análisis externo.

        Parametros:
            Ninguno.

        Retorna:
            list: Una colección de tuplas ordenadas bajo el formato
                  (coeficiente, exponente).
        """
        terminos = []
        actual = self.cabeza
        while actual is not None:
            terminos.append((actual.coeficiente, actual.exponente))
            actual = actual.siguiente
        return terminos

    def esta_vacio(self):
        """
        Verifica la condición de nulidad del sistema algebraico.

        Parametros:
            Ninguno.

        Retorna:
            bool: True si la ecuación es P(x) = 0 (no contiene nodos),
                  False en caso contrario.
        """
        return self.cabeza is None

    def __str__(self):
        """
        Construye la representación simbólica de la ecuación matemática,
        transformando los datos estructurales en una sintaxis legible para
        el análisis humano.

        Parametros:
            Ninguno.

        Retorna:
            str: Una cadena de texto que ilustra el polinomio formal
                 (ejemplo: "4x^3 - 2x^2 + 7").
        """
        if self.esta_vacio():
            return "0"

        partes = []
        actual = self.cabeza
        while actual is not None:
            coef = actual.coeficiente
            expo = actual.exponente
            if expo == 0:
                partes.append(str(coef))
            elif expo == 1:
                partes.append(f"{coef}x^{expo}")
            else:
                partes.append(f"{coef}x^{expo}")
            actual = actual.siguiente

        return " + ".join(partes).replace("+ -", "- ")

    # ─────────────────────────────────────────
    # CONTRACCIÓN TOPOLÓGICA (Prevención de Bucles)
    # ─────────────────────────────────────────

    def simplificar(self):
        """
        Escanea la ecuación y desintegra cualquier término cuyo coeficiente
        haya colapsado a cero tras una operación matemática, asegurando
        que el grado del polinomio sea siempre preciso.

        Parametros:
            Ninguno.

        Retorna:
            Ninguno. Modifica la estructura interna eliminando nodos nulos.
        """
        actual = self.cabeza
        anterior = None

        while actual is not None:
            if actual.coeficiente == 0:
                if anterior is None:
                    self.cabeza = actual.siguiente
                    actual = self.cabeza
                else:
                    anterior.siguiente = actual.siguiente
                    actual = actual.siguiente
            else:
                anterior = actual
                actual = actual.siguiente

    # ─────────────────────────────────────────
    # OPERACIONES ALGEBRAICAS
    # ─────────────────────────────────────────

    def sumar(self, otro):
        """
        Ejecuta la suma algebraica lineal entre dos modelos polinómicos, agrupando
        y operando los términos que comparten el mismo grado.

        Parametros:
            otro (polinomio): La segunda estructura matemática a sumar.

        Retorna:
            polinomio: Una nueva entidad independiente que representa la adición
                       exacta de ambos sistemas.
        """
        if not isinstance(otro, polinomio):
            raise TypeError("Se esperaba un polinomio.")

        resultado = polinomio()
        for coef, exp in self.get_terminos():
            resultado.agregar_termino(coef, exp)
        for coef, exp in otro.get_terminos():
            resultado.agregar_termino(coef, exp)

        resultado.simplificar()
        return resultado

    def restar(self, otro):
        """
        Calcula la diferencia matemática entre dos polinomios. El proceso consiste
        en sumar al polinomio base el inverso aditivo de cada término del polinomio
        sustraendo.

        Parametros:
            otro (polinomio): El polinomio que actuará como sustraendo.

        Retorna:
            polinomio: Una nueva entidad que representa el resultado de la sustracción.
        """
        if not isinstance(otro, polinomio):
            raise TypeError("Se esperaba un polinomio.")

        resultado = polinomio()
        for coef, exp in self.get_terminos():
            resultado.agregar_termino(coef, exp)
        for coef, exp in otro.get_terminos():
            resultado.agregar_termino(-coef, exp)

        resultado.simplificar()
        return resultado

    def multiplicar(self, otro):
        """
        Calcula el producto polinómico expandido. Aplica la ley distributiva
        multiplicando cada coeficiente y sumando los exponentes correspondientes,
        según las leyes de los exponentes.

        Parametros:
            otro (polinomio): El polinomio multiplicador.

        Retorna:
            polinomio: Una nueva estructura resultante del producto cruzado completo.
        """
        if not isinstance(otro, polinomio):
            raise TypeError("Se esperaba un polinomio.")

        resultado = polinomio()
        for c1, e1 in self.get_terminos():
            for c2, e2 in otro.get_terminos():
                resultado.agregar_termino(c1 * c2, e1 + e2)

        resultado.simplificar()
        return resultado

    def dividir(self, otro):
        """
        Aplica el algoritmo clásico de división larga euclidiana para encontrar
        los polinomios cociente y residuo. Garantiza que el grado del residuo sea
        estrictamente inferior al grado del divisor.

        Parametros:
            otro (polinomio): El modelo matemático que actuará como divisor.

        Retorna:
            tuple: Una tupla compuesta por dos objetos de la clase polinomio
                   en el orden (cociente, residuo).
        """
        if otro.esta_vacio():
            raise ZeroDivisionError("No se puede dividir por el polinomio cero.")

        cociente = polinomio()
        residuo = polinomio()

        for coef, exp in self.get_terminos():
            residuo.agregar_termino(coef, exp)

        while (not residuo.esta_vacio() and residuo.get_grado() >= otro.get_grado()):
            coef_factor = residuo.get_coeficiente_lider() // otro.get_coeficiente_lider()
            exp_factor = residuo.get_grado() - otro.get_grado()

            if coef_factor != 0:
                cociente.agregar_termino(coef_factor, exp_factor)
            else:
                break

            for coef, exp in otro.get_terminos():
                residuo.agregar_termino(-coef_factor * coef, exp + exp_factor)

            residuo.simplificar()

        return cociente, residuo

    def evaluar(self, x):
        """
        Sustituye la variable independiente por una magnitud constante dada (x)
        para calcular el valor escalar neto de la expresión.

        Parametros:
            x (int): El escalar que reemplazará a la variable independiente.

        Retorna:
            int: La sumatoria de todos los términos evaluados en el punto x.
        """
        if not isinstance(x, int):
            raise TypeError("Solo se permiten valores enteros para x.")

        resultado = 0
        actual = self.cabeza
        while actual is not None:
            resultado += actual.coeficiente * (x ** actual.exponente)
            actual = actual.siguiente
        return resultado

    def derivar(self):
        """
        Ejecuta la operación de diferenciación sobre la estructura. De acuerdo con
        la regla de la potencia del cálculo diferencial, el exponente de cada término
        multiplica a la base, y el grado del término decrece en una unidad.

        Parametros:
            Ninguno.

        Retorna:
            polinomio: El modelo resultante tras aplicar la primera derivada formal.
        """
        resultado = polinomio()
        actual = self.cabeza
        while actual is not None:
            if actual.exponente > 0:
                resultado.agregar_termino(
                    actual.coeficiente * actual.exponente,
                    actual.exponente - 1
                )
            actual = actual.siguiente

        resultado.simplificar()
        return resultado

"""# Uso y Pruebas

"""

p1 = polinomio()
p1.agregar_termino(1, 3)   # 1x³
p1.agregar_termino(2, 2)   # 2x²
p1.agregar_termino(3, 0)   # 3

p2 = polinomio()
p2.agregar_termino(1, 2)   # 1x²
p2.agregar_termino(2, 1)   # 2x
p2.agregar_termino(1, 0)   # 1

print(f"P1:            {p1}")
print(f"P2:            {p2}")
print(f"Grado P1:      {p1.get_grado()}")
print(f"Cabeza P1:     coef={p1.get_cabeza().coeficiente}, exp={p1.get_cabeza().exponente}")
print(f"Coef. líder:   {p1.get_coeficiente_lider()}")
print(f"Términos P1:   {p1.get_terminos()}")

print("-" * 40)

print(f"P1 + P2:       {p1.sumar(p2)}")
print(f"P1 - P2:       {p1.restar(p2)}")
print(f"P1 * P2:       {p1.multiplicar(p2)}")
print(f"P1 evaluado en x=2:  {p1.evaluar(2)}")
print(f"Derivada P1:   {p1.derivar()}")

print("-" * 40)

cociente, residuo = p1.dividir(p2)
print("P1 / P2:")
print(f"  Cociente:    {cociente}")
print(f"  Residuo:     {residuo}")